version: '3.3'
services:

  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - nexus-data:/nexus-data

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy.conf:/etc/nginx/proxy.conf
      - ./ssl:/ssl
    ports:
      - "80:80"
      - "443:443"

volumes:
  nexus-data:
